services:
  postgres:
    image: postgres:16
    container_name: newron_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d newron"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: newron_backend
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./app:/app/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      SIMILARITY_THRESHOLD: ${SIMILARITY_THRESHOLD}
    ports:
      - "8000:8000"

    develop:
      watch:
        - action: sync          
          path: ./app           
          target: /app/app      
          ignore:
            - __pycache__/
        
        - action: rebuild
          path: ./requirements.txt

volumes:
  postgres_data:
